version: '3'
services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/recordbase
  mongo:
    image: mongo:latest
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    logging:
      driver: "none"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"